baseURL = "https://diegolampre.github.io/definitivo/"
languageCode = "en-us"
title = "DWES Vespertino"
theme= "learn"


[params]
themeVariant= "blue"

[outputs]
home =['HTML','JSON','RSS']



# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[Languages.es]
title = "Documentacion de hugo para tema learn"
weight = 2
languageName = "Español"